FLAGS := -fdiagnostics-color=always \
		 -Wall \
		 -Wpedantic \
		 -std=c11 \
		 -Wextra \
		 -Wshadow \
		 -Wundef \
		 -g3 \
		 -fno-common

introduction:
	gcc ./introduction.c -o introduction.out
	./introduction.out

memory:
	gcc ./memory.c -o memory.out
	./memory.out
