name: Build LaTeX document

on: [push, workflow_dispatch]
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@2.5.0
        with:
          root_file: main.tex
          latexmk_shell_escape: true

      - name: Copy PDF
        run: mkdir publish && cp main.pdf publish/Seminararbeit.pdf

      - name: Get tag for Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: publish/Seminararbeit.pdf
          draft: false
          prerelease: false
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PDF branch
        uses: actions/checkout@v2
        with:
          ref: pdf
          fetch-depth: 0
          path: pdfs

      - name: Copy PDF
        run: |
          # Remove git ref full name from ref to only get the branch name and replace slashes with underscores
          export FILENAME=$(echo "${GITHUB_REF#refs/heads/}.pdf" | sed 's:/:_:')
          cp -f main.pdf pdfs/$FILENAME

      - name: Commit and Push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update PDF for ${{ github.ref }}
          repository: ./pdfs
